### ISSUE TITLE
No Default User Agent Set

### ISSUE THREAD

**Issue by Wiilf** [SuRGeoNix/BitSwarm#10]
There is by default no user agent string set in the client's HTTP request headers. This can result in private-tracker penalties or other reductions in place of policy, libtorrent, trackers and possible utilization of these fields on the tracker-end.  This could be otherwise treated as "Fake-Client" by mainland clients. 

**Changes:**

Tracker.cs

```
static Tracker()
        {
            // Allowing Untrusted SSL Certificates with HttpClient
            ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;
            httpClient.Timeout = new TimeSpan(0, 0, 30); // TODO: Options?
            var clientVersion = new ProductInfoHeaderValue("BitSwarm", "2.4.0");
            httpClient.DefaultRequestHeaders.UserAgent.Add(clientVersion);
        }
```

**Comment by SuRGeoNix** [comment]
Yes, that's probably the Key parameter that I set to 1, I though that it was about the passKey/token but probably is the client identifier. I will review also [Alan's implementation](https://github.com/alanmcgovern/monotorrent/blob/master/src/MonoTorrent.Client/MonoTorrent.Client.Tracker/HTTPTracker.cs) and I will fix those as well.

**Comment by Wiilf** [comment]
I edited my comment - I completely forgot I set that as the key value in the PHP file lol

I have added handling in my announce for this client exclusively now. Much easier server-side testing.

```
if ($_SERVER['HTTP_USER_AGENT'] == 'BitSwarm/2.4.0') {
	$keys = array(
		'downloaded' => true,
		'uploaded' => true,
		'info_hash' => true,
		'peer_id' => true,
		'port' => true,
		'no_peer_id' => false,
		'ip' => false,
		'numwant' => false,
		'event' => false,
		'left' => true,
		'compact' => false,
		'key' => 1,
	);
}
```

**Comment by SuRGeoNix** [comment]
Yesterday, I was able to use the private torrent that you sent. It was downloading with 10Mbits/s.

**Comment by Wiilf** [comment]
Thats wonderful! I sent you a so-so torrent, its hardly the best as I realized later but thats awesome! So as it stands it works, maybe I'll work off my IP and try that way. 

Client reports strange data back compared to the others.

Screenshot of data I get back:

https://gcdn.pbrd.co/images/4oDg4J6jJlYt.jpg

**Comment by SuRGeoNix** [comment]
Check this [one](https://github.com/alanmcgovern/monotorrent/blob/master/src/MonoTorrent.Client/MonoTorrent/PeerID.cs). I will update the agent and version of bitswarm with similar way (also for the Key) and let me know if that works for you.

**Comment by Wiilf** [comment]
I'm in my table right now, the column is VARCHAR - 8 characters

I'll increase it to 50

**Comment by SuRGeoNix** [comment]
For udp it's an Int32 but for http might be a string, not sure, there is no documentation
