### ISSUE TITLE
Firewall Rule - Inbound 

### ISSUE THREAD

**Issue by Wiilf** [SuRGeoNix/BitSwarm#12]
Appears the application never initiates a firewall rule request to the Windows firewall allowing inbound connections, this can be helpful in allowing greater forwarding and connectivity.

For this, and the most forward approach I think is first **add a new reference**, browse COM and point path to
C:\WINDOWS\system32\FirewallAPI.dll

Now add the import
```
using NetFwTypeLib;
```
Next, add a new button to designer - button3

On click event 

```
private void button3_Click(object sender, EventArgs e)
        {
            bool firewallRule = false;
            if (MessageBox.Show("Add a Allow All rule for Windows firewall?", "Confirmation", MessageBoxButtons.OKCancel) == DialogResult.OK)
            {
                // Located in FirewallAPI.dll
                INetFwRule firewallRule = (INetFwRule)Activator.CreateInstance(
                Type.GetTypeFromProgID("HNetCfg.FWRule"));
                firewallRule.Action = (NetFwTypeLib.NET_FW_ACTION_)NET_FW_ACTION_.NET_FW_ACTION_ALLOW;
                firewallRule.Description = "Used to allow all internet access.";
                firewallRule.Direction = NET_FW_RULE_DIRECTION_.NET_FW_RULE_DIR_IN;
                firewallRule.Enabled = true;
                firewallRule.InterfaceTypes = "All";
                firewallRule.Name = "BitSwarm 2.4.4";
                INetFwPolicy2 firewallPolicy = (INetFwPolicy2)Activator.CreateInstance(Type.GetTypeFromProgID("HNetCfg.FwPolicy2"));
                firewallPolicy.Rules.Add(firewallRule);
                firewallRule = true;
            }
            if (firewallRule)
                MessageBox.Show("Firewall rule added successfully.");
        }
```

To remove rule, whether on program exit or by user control
```
firewallPolicy.Rules.Remove("BitSwarm 2.4.4");
```

Unlike most other applications listed by filename (Chrome uses their own name), this taps right into the Windows firewall API so you get the name, the values and directly in. 

Its nice to have the firewall pop up window, but it seems this code bypasses that entirely.

This works 100%.

https://docs.microsoft.com/en-us/windows/win32/api/icftypes/

**Comment by SuRGeoNix** [comment]
Here is the code that I wrote for that if you are interested:

```csharp
public static void AddFirewallRule(string ruleName = null, string path = null)
{
	System.Threading.Tasks.Task.Run(() =>
	{
		if (string.IsNullOrEmpty(ruleName))
			ruleName = "Flyleaf";

		if (string.IsNullOrEmpty(path))
			path = Process.GetCurrentProcess().MainModule.FileName;

		path = $"\"{path}\"";

		// Check if rule already exists
		Process proc = new Process
		{
			StartInfo = new ProcessStartInfo
			{
				FileName        = "cmd",
				Arguments       = $"/C netsh advfirewall firewall show rule name={ruleName} verbose | findstr {path}",
				CreateNoWindow  = true,
				UseShellExecute = false,
				RedirectStandardOutput = true,
				WindowStyle     = ProcessWindowStyle.Hidden
			}
		};

		proc.Start();
		proc.WaitForExit();

		if (proc.StandardOutput.Read() > 0)
			return;

		// Add rule with admin rights
		proc = new Process
		{
			StartInfo = new ProcessStartInfo
			{
				FileName = "cmd",
				Arguments = $"/C netsh advfirewall firewall add rule name={ruleName} dir=in  action=allow enable=yes program={path} profile=any &" +
							   $"netsh advfirewall firewall add rule name={ruleName} dir=out action=allow enable=yes program={path} profile=any",
				Verb = "runas",
				CreateNoWindow = true,
				UseShellExecute = true,
				WindowStyle = ProcessWindowStyle.Hidden
			}
		};

		proc.Start();
		Log($"FW rule \"{ruleName}\" added for {path}");
	});
}
```
Checks if already exists (without admin rights) and if not will add it (with admin rights). This way I don't use any COM references and I use admin rights only for the process and not for my whole app (normally once during the installation of the application)

**Comment by Wiilf** [comment]
I would not assign "any" to profiles. This has been known to be a security issue.

While this may take care of inbound rules for TCP? traffic, it does not consider the ports allocated to Bittorrent traffic you've hardcoded to 11111. 

I have made modifications to Tracker.cs that takes care of port assigned by the GUI, mappings and NAT, all retrieved from the registry. The client is NAT/UPnP capable with dynamic port assignments (with random option, like uTorrent). I have only to implement firewall away from our GUI settings to the Client (BitSwarm) class. 

Your client also has a custom browser prefix now as well. Much like magnet links, however very different with strong CBC-AES hash. BitSwarm confirms hash and starts torrents with a special hash (v1):

Yet again I've invented a BEP for the client, and merged BEP_35 => SwitchHash (our hashed algo that starts a torrent with file list from encrypted link). Client is fully supported (2-way encrypt/decrypt - server/client). We will encrypt traffic next and add a checkbox for that in GUI settings this weekend.

switchtorrents:?id:2735:token:cFVsaHNITEx2WHBjc3N3R250RHlIdXRUTHVpY1o4VUkybnBNcnZaT0JzN3lweVc4Ykd1R3F0NEhGTnZNakx0Uw==

I'll be happy to share anything that may interest you.

**Comment by SuRGeoNix** [comment]
Sure, keep me up to date ;) 

I'm working on a performance update today and I will try to fix it work properly with multiple instances because currently uses some statics where it shouldn't. Feel free to do some beta test when I will have it ready!

**Comment by Wiilf** [comment]
Perfect sounds good!

Yes, that issue had us perform the workaround necessary for single or multiple transfers:

```
static BitSwarm client;
static Torrent torrent = new(client);
static Options opt;
```

Looking forward to update on that.

**Comment by SuRGeoNix** [comment]
Ready, give it a try and let me know!

**Comment by Wiilf** [comment]
May be a delay as I don't currently have the 6.0 SDK - Are you inheriting 6.0 exclusive features, or is this futureproofing the runtime?

**Comment by Wiilf** [comment]
Once I disable Contura, I can access the libraries and implement the changes - .NET 6 is having issues for me

**Comment by SuRGeoNix** [comment]
Yes it's just extends the support to .NET 6. It is not required. However, to run the samples you need it. But you could downgrade to .NET 5 as well

**Comment by Wiilf** [comment]
I'm still running on 4.7.8, it's probably time to move on to .NET 5 or 6
