### ISSUE TITLE
Question about multiple program transport stream

### ISSUE THREAD

**Issue by HamidLaktarash** [SuRGeoNix/BitSwarm#16]
I have one multiple program transport stream (MPTS) with source IP address udp://@228.110.1.1:1234. I wanna develop a program like Mosaic Streaming player that detect available program in udp://@228.110.1.1:1234 till we choose one to play. (demux stream and extract programs baseid on PID or PMT ) this task done in VLC app but i cant switch between program and play one of theme، whiles DVB Viewer app play this stream in programs properly. my platform is .net and i am familiar with Flyleaf (your player) and libVLCSharp and ffplay and DVB viewer

`Core.Initialize();

_libVLC = new LibVLC();
_mediaPlayer = new MediaPlayer(_libVLC);

videoView.MediaPlayer = _mediaPlayer;
            
_mediaPlayer.Play(new Media(_libVLC, new Uri("... stream ip ...")));`

Do you have any idea for this task?

**Comment by SuRGeoNix** [comment]
Hi @HamidLaktarash, wrong repository but it's ok.

Check [Wiki](https://github.com/SuRGeoNix/Flyleaf/wiki/Player-(Open)) and Player.MainDemuxer.Programs

You can open the input without default programs/streams and choose which one to open afterwards by checking the available programs/streams.
