### ISSUE TITLE
Other Purposes?

### ISSUE THREAD

**Issue by furesoft** [SuRGeoNix/BitSwarm#5]
can i use your lib to use it for other purposes not for sending files. i want to build a p2p application based on bittorrent for sending/recieving data

**Comment by SuRGeoNix** [comment]
Even I'm not sure what are your purposes, I guess as is will not work. But probably, you could use it as base for you own implementation. The more your implementation matches to bittorrent protocol the less work you will do. Be noticed, that bitswarm does not implement sending yet! (that will be another issue)
