### ISSUE TITLE
Private Torrents do not connect!

### ISSUE THREAD

**Issue by Wiilf** [SuRGeoNix/BitSwarm#9]
I have fully implemented this into a nice list control with internal BLOB fetch and save/load (and client begins downloads, like limewire sort of). 

Works perfect on public torrents, but Private is not possible! uTorrent has absolutely no issues. I cant turn off Private flag in the metadata because that changes the info_hash (database mismatch, seedbox issues etc).

I will investigate but can you please provide a solution or confirmation? 

I cant figure it out, I feel it is this line in Tracker.cs

`byte[] sendBuff = System.Text.Encoding.UTF8.GetBytes($"GET {uri.AbsolutePath}?info_hash={Utils.StringHexToUrlEncode(options.InfoHash)}&peer_id={Utils.StringHexToUrlEncode(BitConverter.ToString(options.PeerId).Replace("-",""))}&port=11111&left={left}&downloaded={downloaded}&uploaded={uploaded}&event=started&compact=1&numwant={num_want} HTTP/1.1\r\nHost: {host}:{port}\r\nConection: close\r\n\r\n");`

I plan to extend this codebase and push this thing forward. I already have it doing a lot, like notifications and much more, really cool library, thank you!

**Comment by Wiilf** [comment]
I have spent 4 days straight studying your project and I really was hoping this part worked, kind of thing I didnt expect as it is simply a Url and passkey hash param (/announce?passkey=xxx)

Okay thanks, I'll look to implementing it and sourcing other codebases for insight in their implementations and port over.

**Comment by Wiilf** [comment]
Absolutely, lets do this. Like I said I've hauled some major time at this so its very friend-client based now and the general classes/BEPs also have several IntelliSense "simplify" changes to shorten the code, its coming out cleaner.

**Comment by SuRGeoNix** [comment]
I have not included LTDP cause I thought is old and not really useful. Which IPv6 issue are you talking about? Let me know what do you want to include (eg. for Private trackers, if you know how they work explain me, give me some refs and I will try to include them myself)

**Comment by SuRGeoNix** [comment]
OK, that's not easy to implement as there is no specification and with your test private torrent I get a lot of timeouts from the tracker. I have noticed the following.

1) There is no standard (BEP) to explain how you should send token/passkey/key parameters
2) HTTP has at least 2 issues in my library a) will not follow / set cookies b) the receive timeout is too small
3) Your private tracker will response with the following after a lot of tries with timeouts

SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transactiond14:failure reason17:Cant insert peer.e

which doesn't make sense to me
